<?xml version="1.0" encoding="UTF-8"?>
<!-- This wsdl file is for an XCA Initiating Gateway Actor which
     implements the XDS Affinity Domain Option.  It contains only the Query
     portion of the interface due to the split of web services endpoints
     to support MTOM versus non-MTOM processing.  -->
<!-- 
  IHE Cross Community Access (XCA) WSDL defintions for Initiating Gateway Query
  -->
<definitions 		
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:ihe="urn:ihe:iti:xds-b:2007" 
    xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" 
    xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
    targetNamespace="urn:ihe:iti:xds-b:2007" 
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
    xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
    name="InitiatingGateway_Query">
	<documentation>IHE XCA Initiating Gateway Query</documentation>
	<types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" 
       schemaLocation="../schema/ebRS/rs.xsd"/>
			<xsd:import namespace="urn:ihe:iti:xds-b:2007" 
       schemaLocation="../schema/IHE/XDS.b_DocumentRepository.xsd"/>
      <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"  
        schemaLocation="../schema/ebRS/query.xsd"/>
		</xsd:schema>
	</types>
    <message name="RegistryStoredQuery_Message">
    <documentation>Registry Stored Query</documentation>
    <part name="body" element="query:AdhocQueryRequest"  />
    </message>
    <message name="RegistryStoredQueryResponse_Message">
    <documentation>Registry Stored Query Response</documentation>
    <part name="body" element="query:AdhocQueryResponse" />
    </message>

  <portType name="InitiatingGatewayQuery_PortType">
    <operation name="DocumentRegistry_RegistryStoredQuery">
    <input message="ihe:RegistryStoredQuery_Message"
    wsaw:Action="urn:ihe:iti:2007:RegistryStoredQuery" />
    <output message="ihe:RegistryStoredQueryResponse_Message"
    wsaw:Action="urn:ihe:iti:2007:RegistryStoredQueryResponse" />
    </operation>
 
 </portType>



	<binding name="InitiatingGatewayQuery_Binding_Soap" type="ihe:InitiatingGatewayQuery_PortType">
      <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

  <!-- Added to support Affinity Domain option -->
    <operation name="DocumentRegistry_RegistryStoredQuery">
      <soap12:operation soapAction="urn:ihe:iti:2007:RegistryStoredQuery" />
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
    
  </binding>
  
      <service name="InitiatingGatewayQuery_Service">
        <port name="InitiatingGatewayQuery_Port_Soap12" binding="ihe:InitiatingGatewayQuery_Binding_Soap12">
		  <soap12:address location="http://servicelocation/InitiatingGatewayQuery_Service"/>
		</port>
	  </service>
</definitions>